export const Products = [
  {
    id: 1,
    title: "Organic Mangoes",
    price: 15.99,
    rating: 4.8,
    color: ["Yellow", "Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/mango-1.jpg", "/mango-2.jpg"],
    description: "Fresh, organic mangoes directly from the farm.",
    category: "Fruits",
    subCategory: "Tropical",
    material: "Organic",
    careInstructions: "Keep in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "John Doe",
        userImage: "/user1.jpg",
        rating: 5,
        comment: "Sweet and juicy, perfect for smoothies!",
      },
    ],
  },
  {
    id: 2,
    title: "Fresh Tomatoes",
    price: 12.49,
    rating: 4.7,
    color: ["Red"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/tomato-1.jpg", "/tomato-2.jpg"],
    description: "Ripe, fresh tomatoes ideal for salads and cooking.",
    category: "Vegetables",
    subCategory: "Roots",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Jane Smith",
        userImage: "/user2.jpg",
        rating: 4.5,
        comment: "Great quality, very fresh and tasty.",
      },
    ],
  },
  {
    id: 3,
    title: "Organic Bananas",
    price: 9.99,
    rating: 4.6,
    color: ["Yellow", "Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/banana-1.jpg", "/banana-2.jpg"],
    description: "Delicious organic bananas, perfect for snacking.",
    category: "Fruits",
    subCategory: "Tropical",
    material: "Organic",
    careInstructions: "Keep in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Emily Johnson",
        userImage: "/user3.jpg",
        rating: 4.7,
        comment: "Very fresh and tasty bananas.",
      },
    ],
  },
  {
    id: 4,
    title: "Farm Fresh Eggs",
    price: 6.99,
    rating: 4.9,
    color: ["White", "Brown"],
    size: ["12 eggs", "24 eggs"],
    image: ["/eggs-1.jpg", "/eggs-2.jpg"],
    description: "High-quality farm fresh eggs.",
    category: "Dairy",
    subCategory: "Eggs",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Michael Brown",
        userImage: "/user4.jpg",
        rating: 5,
        comment: "Very fresh and delicious eggs.",
      },
    ],
  },
  {
    id: 5,
    title: "Fresh Cucumbers",
    price: 8.49,
    rating: 4.7,
    color: ["Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/cucumber-1.jpg", "/cucumber-2.jpg"],
    description: "Crisp and fresh cucumbers perfect for salads.",
    category: "Vegetables",
    subCategory: "Roots",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Lisa Green",
        userImage: "/user5.jpg",
        rating: 4.6,
        comment: "Very fresh and crispy.",
      },
    ],
  },
  {
    id: 6,
    title: "Fresh Carrots",
    price: 7.99,
    rating: 4.5,
    color: ["Orange"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/carrot-1.jpg", "/carrot-2.jpg"],
    description: "Sweet and crunchy fresh carrots.",
    category: "Vegetables",
    subCategory: "Roots",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "David Wilson",
        userImage: "/user6.jpg",
        rating: 4.7,
        comment: "Perfect for juicing and salads.",
      },
    ],
  },
  {
    id: 7,
    title: "Fresh Pineapples",
    price: 14.99,
    rating: 4.8,
    color: ["Yellow"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/pineapple-1.jpg", "/pineapple-2.jpg"],
    description: "Sweet and tangy fresh pineapples.",
    category: "Fruits",
    subCategory: "Tropical",
    material: "Organic",
    careInstructions: "Keep in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Sophia Turner",
        userImage: "/user7.jpg",
        rating: 5,
        comment: "Very sweet and juicy!",
      },
    ],
  },
  {
    id: 8,
    title: "Fresh Lettuce",
    price: 5.99,
    rating: 4.6,
    color: ["Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/lettuce-1.jpg", "/lettuce-2.jpg"],
    description: "Crisp and fresh lettuce for salads and sandwiches.",
    category: "Vegetables",
    subCategory: "Leaves",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Oliver White",
        userImage: "/user8.jpg",
        rating: 4.5,
        comment: "Very fresh and crunchy.",
      },
    ],
  },
  {
    id: 9,
    title: "Fresh Spinach",
    price: 6.49,
    rating: 4.8,
    color: ["Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/spinach-1.jpg", "/spinach-2.jpg"],
    description: "Nutritious and fresh spinach leaves.",
    category: "Vegetables",
    subCategory: "Leaves",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Sophia Miller",
        userImage: "/user9.jpg",
        rating: 4.9,
        comment: "Very fresh and healthy.",
      },
    ],
  },
  {
    id: 10,
    title: "Fresh Papayas",
    price: 11.99,
    rating: 4.7,
    color: ["Orange", "Green"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/papaya-1.jpg", "/papaya-2.jpg"],
    description: "Sweet and ripe papayas from the farm.",
    category: "Fruits",
    subCategory: "Tropical",
    material: "Organic",
    careInstructions: "Keep in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Liam Taylor",
        userImage: "/user10.jpg",
        rating: 4.8,
        comment: "Very sweet and delicious.",
      },
    ],
  },
  {
    id: 11,
    title: "Fresh Oranges",
    price: 10.99,
    rating: 4.6,
    color: ["Orange"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/orange-1.jpg", "/orange-2.jpg"],
    description: "Juicy and fresh oranges perfect for juicing.",
    category: "Fruits",
    subCategory: "Citrus",
    material: "Organic",
    careInstructions: "Keep in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Noah Anderson",
        userImage: "/user11.jpg",
        rating: 4.7,
        comment: "Very fresh and juicy.",
      },
    ],
  },
  {
    id: 12,
    title: "Fresh Potatoes",
    price: 8.99,
    rating: 4.5,
    color: ["Brown"],
    size: ["1 kg", "2 kg", "5 kg"],
    image: ["/potato-1.jpg", "/potato-2.jpg"],
    description: "High-quality fresh potatoes from local farms.",
    category: "Vegetables",
    subCategory: "Roots",
    material: "Organic",
    careInstructions: "Store in a cool, dry place",
    inStock: true,
    reviews: [
      {
        userName: "Emma Thomas",
        userImage: "/user12.jpg",
        rating: 4.6,
        comment: "Great for cooking, very fresh.",
      },
    ],
  },
];
